# Generated by Django 4.1.7 on 2023-03-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter name', max_length=150, null=True, verbose_name='Name')),
                ('telegram_id', models.CharField(help_text='Enter telegram ID', max_length=30, unique=True, verbose_name='Telegram ID')),
                ('language', models.CharField(default='uz', help_text='Enter language', max_length=4, verbose_name='Language')),
                ('phone', models.CharField(blank=True, help_text='Enter phone number', max_length=20, null=True, verbose_name='Phone number')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BotUser',
                'verbose_name_plural': 'BotUser',
                'db_table': 'BotUser',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category', max_length=150, verbose_name='Category')),
                ('name_uz', models.CharField(help_text='Enter category', max_length=150, null=True, verbose_name='Category')),
                ('name_ru', models.CharField(help_text='Enter category', max_length=150, null=True, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.botuser', to_field='telegram_id', verbose_name='Bot User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter product name', max_length=150, null=True, verbose_name='Product')),
                ('name_uz', models.CharField(blank=True, help_text='Enter product name', max_length=150, null=True, verbose_name='Product')),
                ('name_ru', models.CharField(blank=True, help_text='Enter product name', max_length=150, null=True, verbose_name='Product')),
                ('image', models.ImageField(blank=True, help_text='Upload image', null=True, upload_to='product-images', verbose_name='Image')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_uz', models.TextField(blank=True, null=True, verbose_name='About')),
                ('about_ru', models.TextField(blank=True, null=True, verbose_name='About')),
                ('price', models.IntegerField(blank=True, help_text='Enter price', null=True, verbose_name='Price')),
                ('discount', models.IntegerField(blank=True, help_text='Enter discount', null=True, verbose_name='Discount')),
                ('category', models.ForeignKey(help_text='Choose category', on_delete=django.db.models.deletion.CASCADE, to='myapp.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.botuser', to_field='telegram_id', verbose_name='Bot User')),
            ],
        ),
    ]
