# Generated by Django 4.1.7 on 2023-03-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_locations_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter subcategory', max_length=150, verbose_name='Subcategory')),
                ('name_uz', models.CharField(help_text='Enter subcategory', max_length=150, null=True, verbose_name='Subcategory')),
                ('name_ru', models.CharField(help_text='Enter subcategory', max_length=150, null=True, verbose_name='Subcategory')),
                ('category', models.ForeignKey(help_text='Choose category', on_delete=django.db.models.deletion.CASCADE, to='myapp.category', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Choose category', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory', verbose_name='Category'),
        ),
    ]
